### ISSUE TITLE
Schedule for next release

### ISSUE THREAD

**Issue by akki** [preset-io/elasticsearch-dbapi#12]
Hi

I was trying to use your library when trying to setup Superset to be used with Elasticsearch.
I found that using the URL `elasticsearch+http://localhost:9200` did not work for me with the latest version of the library.

This is the stack trace:
```
ERROR:superset.views.base:must be str, not NoneType
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 106, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 168, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/core.py", line 1367, in testconn
    a = engine.connect()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2209, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2307, in raw_connection
    self.pool.unique_connection, _connection
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/es/elastic/api.py", line 32, in connect
    return Connection(host, port, path, scheme, user, password, context, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/es/elastic/api.py", line 109, in __init__
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/es/baseapi.py", line 57, in __init__
    self.url = parse.urlunparse((scheme, netloc, path, None, None, None))
  File "/usr/local/lib/python3.6/urllib/parse.py", line 479, in urlunparse
    return _coerce_result(urlunsplit((scheme, netloc, url, query, fragment)))
  File "/usr/local/lib/python3.6/urllib/parse.py", line 491, in urlunsplit
    url = '//' + (netloc or '') + url
TypeError: must be str, not NoneType
```

I see that the error doesn't happen with your current `master` branch (was fixed in https://github.com/preset-io/elasticsearch-dbapi/commit/9aff5e4f6459fba4ea9cc244196f792b5ff36582) although I am not sure if this was the intended fix. Also, I was using `Python3.6` but this error might not show up in `Python3.8` but I have not looked into the code very deeply.

So I wanted to know when you plan to release your current master?

**Comment by akki** [comment]
I had installed this library using `pip install elasticsearch-dbapi` when I hit this issue/bug.

**Comment by willbarrett** [comment]
Hi @akki - we're working on cutting the `0.36` release now, but we've hit a few roadblocks. Don't quote me on this, but I imagine it will be out in the next week barring any further complications. If you want to follow along, the `apache-releases` channel in the Superset Slack workspace is a great place to look.

**Comment by akki** [comment]
Is it https://superset.slack.com? 

Seems like I cannot join it 🤔 (says "if you have `@superset.io` email, you can create an account" and my existing Slack credentials don't work).


Anyways, I'll close this issue since I now know the right place for this question. Thanks for the quick reply!

**Comment by willbarrett** [comment]
@akki `apache-superset.slack.com` is what you're looking for. Here's the link to join provided in the README: https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU
