### ISSUE TITLE
Opendistro : Create table from apache superset

### ISSUE THREAD

**Issue by jhonnymadera** [preset-io/elasticsearch-dbapi#25]
Table [logicaghl_sigeco_roomsales] could not be found, please double check your database connection, schema, and table name, error: (es.exceptions.ProgrammingError) Table "logicaghl_sigeco_roomsales" not found [SQL: SHOW COLUMNS FROM "logicaghl_sigeco_roomsales"] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by markharding** [comment]
Same issue with AWS ES 7.4.

```
127.0.0.1 - - [15/Jun/2020:17:49:08 +0000] "GET /tablemodelview/add HTTP/1.1" 200 3143 "http://localhost:8088/tablemodelview/list/?_flt_1_is_sqllab_view=y" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): vpc-tf-test-xwjmn7jl5jezboiwtdmor3diyq.us-east-1.es.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://vpc-tf-test-xwjmn7jl5jezboiwtdmor3diyq.us-east-1.es.amazonaws.com:443 "POST /_opendistro/_sql/ HTTP/1.1" 200 884
INFO:elasticsearch:POST https://vpc-tf-test-xwjmn7jl5jezboiwtdmor3diyq.us-east-1.es.amazonaws.com:443/_opendistro/_sql/ [status:200 request:0.076s]
DEBUG:elasticsearch:> {"query":"SHOW TABLES LIKE snowplow-es"}
DEBUG:elasticsearch:< {
  "schema": [
    {
      "name": "TABLE_CAT",
      "type": "keyword"
    },
    {
      "name": "TABLE_SCHEM",
      "type": "keyword"
    },
    {
      "name": "TABLE_NAME",
      "type": "keyword"
    },
    {
      "name": "TABLE_TYPE",
      "type": "keyword"
    },
    {
      "name": "REMARKS",
      "type": "keyword"
    },
    {
      "name": "TYPE_CAT",
      "type": "keyword"
    },
    {
      "name": "TYPE_SCHEM",
      "type": "keyword"
    },
    {
      "name": "TYPE_NAME",
      "type": "keyword"
    },
    {
      "name": "SELF_REFERENCING_COL_NAME",
      "type": "keyword"
    },
    {
      "name": "REF_GENERATION",
      "type": "keyword"
    }
  ],
  "total": 1,
  "datarows": [[
    "511275270616:tf-test",
    null,
    "snowplow-es",
    "BASE TABLE",
    null,
    null,
    null,
    null,
    null,
    null
  ]],
  "size": 1,
  "status": 200
}
Got an error in pre_add for snowplow-es
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/es/baseapi.py", line 25, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 148, in execute
    return self._show_columns(re_table_name[1])
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 129, in _show_columns
    raise exceptions.ProgrammingError(f"Table {table_name} not found")
es.exceptions.ProgrammingError: Table "snowplow-es" not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/views/base.py", line 213, in validate_sqlatable
    table.get_sqla_table_object()
  File "/app/superset/connectors/sqla/models.py", line 1150, in get_sqla_table_object
    return self.database.get_table(self.table_name, schema=self.schema)
  File "/app/superset/models/core.py", line 594, in get_table
    autoload_with=self.get_sqla_engine(),
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 507, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 502, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 596, in _init
    resolve_fks=resolve_fks,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 620, in _autoload
    _extend_on=_extend_on,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2172, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1624, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 661, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 388, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "/usr/local/lib/python3.6/site-packages/es/basesqlalchemy.py", line 170, in get_columns
    result = connection.execute(query)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1151, in _execute_text
    parameters,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/es/baseapi.py", line 25, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 148, in execute
    return self._show_columns(re_table_name[1])
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 129, in _show_columns
    raise exceptions.ProgrammingError(f"Table {table_name} not found")
sqlalchemy.exc.ProgrammingError: (es.exceptions.ProgrammingError) Table "snowplow-es" not found
[SQL: SHOW COLUMNS FROM "snowplow-es"]
(Background on this error at: http://sqlalche.me/e/f405)
ERROR:superset.views.base:Got an error in pre_add for snowplow-es
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/es/baseapi.py", line 25, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 148, in execute
    return self._show_columns(re_table_name[1])
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 129, in _show_columns
    raise exceptions.ProgrammingError(f"Table {table_name} not found")
es.exceptions.ProgrammingError: Table "snowplow-es" not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/views/base.py", line 213, in validate_sqlatable
    table.get_sqla_table_object()
  File "/app/superset/connectors/sqla/models.py", line 1150, in get_sqla_table_object
    return self.database.get_table(self.table_name, schema=self.schema)
  File "/app/superset/models/core.py", line 594, in get_table
    autoload_with=self.get_sqla_engine(),
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 507, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 502, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 596, in _init
    resolve_fks=resolve_fks,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 620, in _autoload
    _extend_on=_extend_on,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2172, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1624, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 661, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 388, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "/usr/local/lib/python3.6/site-packages/es/basesqlalchemy.py", line 170, in get_columns
    result = connection.execute(query)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1151, in _execute_text
    parameters,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/es/baseapi.py", line 25, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 148, in execute
    return self._show_columns(re_table_name[1])
  File "/usr/local/lib/python3.6/site-packages/es/opendistro/api.py", line 129, in _show_columns
    raise exceptions.ProgrammingError(f"Table {table_name} not found")
sqlalchemy.exc.ProgrammingError: (es.exceptions.ProgrammingError) Table "snowplow-es" not found
[SQL: SHOW COLUMNS FROM "snowplow-es"]
(Background on this error at: http://sqlalche.me/e/f405)
127.0.0.1 - - [15/Jun/2020:17:49:14 +0000] "POST /tablemodelview/add HTTP/1.1" 302 339 "http://localhost:8088/tablemodelview/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
127.0.0.1 - - [15/Jun/2020:17:49:14 +0000] "GET /tablemodelview/list/?_flt_1_is_sqllab_view=y HTTP/1.1" 200 3509 "http://localhost:8088/tablemodelview/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"


```

**Comment by dpgaspar** [comment]
A new version is out `0.2.0`, that brings much better support for opendistro. You can test this problem against it. 
Going to close this issue, feel free to reopen if the problem persists
