### ISSUE TITLE
Connecting to opendistro from Apache Superset throws SQL parse exception

### ISSUE THREAD

**Issue by syamat** [preset-io/elasticsearch-dbapi#5]
The following error is thrown while creating a new Database connection on  Open Distro 1.2.0 after installing opendistro plugin using "pip install elasticsearch-dbapi[aws]".
The connection string I gave is "odelasticsearch+http://localhost:9200/"
*Incoming request /_opendistro/_sql/?format=csv: SELECT 1
[2019-12-16T09:30:14,137][ERROR][c.a.o.s.p.RestSqlAction  ] [ATVDI] 77d855ee-1f9e-411c-a79f-464860adcba7 Client side error during query execution
java.lang.NullPointerException: null
	at com.amazon.opendistroforelasticsearch.sql.parser.SqlParser.parseSelect(SqlParser.java:71) ~[opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at com.amazon.opendistroforelasticsearch.sql.parser.SqlParser.parseSelect(SqlParser.java:60) ~[opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at com.amazon.opendistroforelasticsearch.sql.query.ESActionFactory.create(ESActionFactory.java:87) ~[opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.SearchDao.explain(SearchDao.java:59) ~[opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.explainRequest(RestSqlAction.java:156) [opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.prepareRequest(RestSqlAction.java:127) [opendistro_sql-1.2.0.0.jar:1.2.0.0]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:92) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:240) [elasticsearch-7.2.0.jar:7.2.0]*

**Comment by dpgaspar** [comment]
Hi @syamat,

Are you doing `SELECT 1` ? does it work with other type's of select statements?

**Comment by syamat** [comment]
No, I just clicked the "Test Connection" button while creating a "Database"in Superset that connects to a OD instance. Screenshot is attached.
![Screenshot at 2019-12-19 12-46-50](https://user-images.githubusercontent.com/10418735/71152996-fbcc6200-225d-11ea-9629-4ddcbebaafad.png)

**Comment by syamat** [comment]
It seems the issue is only which clicking the Test Connection, the connection works in SQL Lab when query.

**Comment by dpgaspar** [comment]
Yes exactly. Yet, I'll implement a `select 1` proxy for it

**Comment by markharding** [comment]
@dpgaspar is there a work around for this?
I am currently still getting (open distro AWS 7.4)
```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [<EOF>] at: 'SELECT 1' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}
```

**Comment by dai-chen** [comment]
@dpgaspar FYI, We've been currently working on a new query engine for ODFE SQL plugin with many improvements. This issue is already fixed in PR: https://github.com/opendistro-for-elasticsearch/sql/pull/542. The new engine is experimental and disabled by default. You can follow the instruction here to preview: https://github.com/opendistro-for-elasticsearch/sql#experimental

**Comment by dpgaspar** [comment]
This is supported on 0.2.0 released today
