### ISSUE TITLE
packaging missing from requirements?

### ISSUE THREAD

**Issue by xylar** [preset-io/elasticsearch-dbapi#56]
In the conda-forge build, I'm seeing:
```
import: 'es'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1618938422964/test_tmp/run_test.py", line 2, in <module>
    import es
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1618938422964/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/es/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1618938422964/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/es/elastic/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1618938422964/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/es/elastic/api.py", line 15, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

It looks like this import was added 3 hours ago.  Is `packaging` now a requirement, and did this get missed from `setup.py`?

**Comment by xylar** [comment]
https://github.com/conda-forge/elasticsearch-dbapi-feedstock/pull/3

**Comment by dpgaspar** [comment]
@xylar thanks for reporting this a fix is on the way

**Comment by dpgaspar** [comment]
ok 0.2.3 is out, can you re check it?
