### ISSUE TITLE
`six` not listed in package install requirements

### ISSUE THREAD

**Issue by xylar** [preset-io/elasticsearch-dbapi#83]
On the conda-forge build of the latest release, we're seeing:
```
import: 'es'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1644514257214/test_tmp/run_test.py", line 2, in <module>
    import es
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1644514257214/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/es/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1644514257214/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/es/elastic/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1644514257214/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/es/elastic/api.py", line 6, in <module>
    from es.baseapi import (
  File "/home/conda/feedstock_root/build_artifacts/elasticsearch-dbapi_1644514257214/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/es/baseapi.py", line 7, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

See:
https://github.com/conda-forge/elasticsearch-dbapi-feedstock/pull/9

`six` is not listed under `install_requires`:
https://github.com/preset-io/elasticsearch-dbapi/blob/0.2.8/setup.py#L31
but it seems like it probably needs to be.

**Comment by dpgaspar** [comment]
Right you are, this passed has six is installed with the requirements-dev. I'll make a fix and release ASAP

**Comment by dpgaspar** [comment]
fixed and released
